version: "3.9"

services:
  client-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client-service
    ports:
      - "5003:5000"

  scheduler-service:
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    container_name: scheduler-service
    environment:
      - MAIN_APP_URL=http://client-service:5000
